### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by sdogruyol** [benoist/carbon-crystal#4]
Would you mind adding Travis CI support to your project? 

You can also add a build status badge to your README

**Comment by sdogruyol** [comment]
Currently the build fails on master because of `openssl` package

**Comment by benoist** [comment]
Yeah I'll allow failures on the latest release for now

**Comment by sdogruyol** [comment]
:+1:

**Comment by sdogruyol** [comment]
Meanwhile are you going to make a public release soon?

**Comment by benoist** [comment]
Not yet. Still got lots to do, but when the time comes I would love a link in the Crystal weekly ;-)

**Comment by benoist** [comment]
Hopefully I will have something ready publicly releasable the first week of the new year

**Comment by sdogruyol** [comment]
I'd be happy to share it on Crystal Weekly :+1:

**Comment by benoist** [comment]
Cool :). I've updated the readme with the goal of being able to create a blogging system in 15 mins :)

**Comment by sdogruyol** [comment]
Wow that's pretty bold :) But i think you can accomplish it with the power of Crystal :+1:
